
  build:
     command: npm run build:ssr
     commandOrigin: config
     publish: /opt/build/repo/dist/personal-portfolio/browser
     publishOrigin: config
   plugins:
     - inputs: {}
       origin: config
       package: "@netlify/angular-runtime"
