[build]
  command = "npm run build:ssr"
  commandOrigin = "config"
  publish = "dist/personal-portfolio/browser"
  publishOrigin = "config"

[[plugins]]
  package = "@netlify/angular-runtime"
  origin = "config"
  [plugins.inputs]
